---
version: "3"
services:
  web:
    build:
      context: ./
      dockerfile: ./docker/web/Dockerfile
    image: ${APP_NAME}-web:${APP_VERSION}
    working_dir: /var/www
    ports:
      - "0.0.0.0:80:80/tcp"
      - "0.0.0.0:443:443/tcp"
  app:
    build:
      context: ./
      dockerfile: ./docker/app/Dockerfile
    image: ${APP_NAME}-app:${APP_VERSION}
    working_dir: /var/www
    expose:
      - "9000/tcp"
    environment:
      - APP_NAME
      - APP_ENV
      - APP_KEY
      - APP_DEBUG
      - APP_URL
      - APP_VERSION
      - LOG_CHANNEL
      - DB_CONNECTION
      - DB_HOST
      - DB_PORT
      - DB_DATABASE
      - DB_USERNAME
      - DB_PASSWORD
      - BROADCAST_DRIVER
      - CACHE_DRIVER
      - QUEUE_CONNECTION
      - SESSION_DRIVER
      - SESSION_LIFETIME
      - REDIS_HOST
      - REDIS_PASSWORD
      - REDIS_PORT
      - MAIL_MAILER
      - MAIL_HOST
      - MAIL_PORT
      - MAIL_USERNAME
      - MAIL_PASSWORD
      - MAIL_ENCRYPTION
      - MAIL_FROM_ADDRESS
      - MAIL_FROM_NAME
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_DEFAULT_REGION
      - AWS_BUCKET
      - PUSHER_APP_ID
      - PUSHER_APP_KEY
      - PUSHER_APP_SECRET
      - PUSHER_APP_CLUSTER
      - MIX_PUSHER_APP_KEY
      - MIX_PUSHER_APP_CLUSTER
  db:
    image: mariadb:10
    ports:
      - "0.0.0.0:3306:3306/tcp"
    volumes:
      - ./docker/volumes/db:/var/lib/mysql
    tmpfs: /tmp
    environment:
      - "MYSQL_DATABASE=${DB_DATABASE}"
      - "MYSQL_USER=${DB_USERNAME}"
      - "MYSQL_PASSWORD=${DB_PASSWORD}"
      - "MYSQL_ROOT_PASSWORD=${DB_PASSWORD}"
